### PR TITLE
Check last bit when checking parity

### PR DESCRIPTION
**Pull request by smu160**
Hi,

This is a simple PR that should take care of the `TODO can be faster (check last bit)` comment. I ran the tests as specified in CONTRIBUTING.md, and everything passes. Please let me know if any additional information is needed.

Thank you!

### CODE REVIEW

**Comment by jvdd** [comment]
Hey @smu160

Thanks for contributing to this library!

I just checked what this optimization would look like in assembly & it turns out that the Rust compiler already performs this optimization: https://godbolt.org/z/9v3qoPrdr
(I also checked this for the %4 operations & can confirm that Rust compiles this to `& 3`)

Since Rust takes already care of this, I think leaving the current implementation is best w.r.t. code readability.

If you revert the code changes & keep the TODO deleted, I will merge this PR :) 

I really appreciate you taking the time for this, without this PR the TODO would not have been investigated

P.S.: there seems to be an issue with the `tsdownsample` CI - focussing on the Python bindings. The CI for the Rust code passes!

**Review by jvdd — CHANGES_REQUESTED** [review]
You can keep the TODO removed, but may revert your changes.

**Comment by jvdd** [comment]
Failing CI has been resolved in #18

**Comment by smu160** [comment]
@jvdd 

Thank you for getting back to me. I reverted my previous commit, and simply removed the `TODO` comment. The tests for the rust code still pass. Please let me know if there's anything else that needs to be done.

Thank you!

**Review by jvdd — APPROVED** [review]

**Comment by jvdd** [comment]
Thanks for applying the requested changes! 

If you are interested in further contributing to this library, I would suggest having a look over here: https://github.com/predict-idlab/tsdownsample/issues/5#issuecomment-1386828771or skimming through the [Issues](https://github.com/predict-idlab/tsdownsample/issues).

You have the honor to be the first (external) contributor to this project!! :tada:

**Pull request merged**
